yname: Report de bug
description: Report un bug sur un plugin Squid
title: "[BUG]"
labels: 
  - Bug, 
  - New
assignees: []

body:
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Une description claire et concise de la nature du bug.
    validations:
      required: true

  - type: textarea
    id: step_to_reproduce
    attributes:
      label: Étapes à suivre pour reproduire le bug
      description: 1. Faire '...', 2. Cliquer sur '...' ...
    validations:
      required: true
      
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
      description: 'Une description claire et concise de ce que ça doit faire si ce n''était pas un bug.'

  - type: input
    id: date
    attributes:
      label: Date et heure de la production du bug
    validations:
      required: true

  - type: dropdown
    id: plugin
    validations:
      required: true
    attributes:
      label: Plugin
      description: Quel plugin Squid ?
      options:
        - SquidHome
        - SquidEco
        - SquidPortal
        - SquidMarket
        - SquidSync
        - Autre


  - type: textarea
    id: video-screen
    attributes:
      label: 'Screen / vidéo'
      description: 'Le cas échéant, ajoutez des captures d''écran et/ou vidéos pour expliquer votre problème'


  - type: textarea
    id: plugin-info
    attributes:
      label: 'Information du plugin'
      description: 'Le nom et la version du plugin accessible via la commande /version <PluginName>'


  - type: textarea
    id: more-info
    attributes:
      label: 'Information supplémentaire'
      description: 'Ajoutez ici tout autre contexte relatif au problème.'
